<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>8o</string>
	</array>
	<key>name</key>
	<string>Octo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single line comments</string>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Data registers</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?i:v\h)(?=$|\s)</string>
			<key>name</key>
			<string>variable.language.vreg.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Address register</string>
			<key>match</key>
			<string>(?&lt;=^|\s)i(?=$|\s)</string>
			<key>name</key>
			<string>variable.language.ireg.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assignment operators</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:\:=|\+=|\-=|=\-|\|=|&amp;=|\^=|&lt;&lt;=|&gt;&gt;=)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.operator.assignment.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comparison operators</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:==|!=|&lt;=|&gt;=|&lt;|&gt;)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.operator.comparison.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control flow keywords</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:return|if|then|begin|else|end|loop|again|while|jump|jump0|\;)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.control.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>alias and const directives</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:\:alias|\:const)(?=$|\s)</string>
			<key>name</key>
			<string>storage.type.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Self-modifying code commands</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:\:unpack|\:next|\:org)(?=$|\s)</string>
			<key>name</key>
			<string>support.function.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Metaprogramming commands</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:\:macro|\:calc|\:byte)(?=$|\s)</string>
			<key>name</key>
			<string>support.function.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Breakpoint command</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:\:breakpoint)(?=$|\s)</string>
			<key>name</key>
			<string>support.function.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Deprecated commands</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(\:proto)(?=$|\s)</string>
			<key>name</key>
			<string>invalid.deprecated.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Statement keywords (standard)</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:clear|bcd|save|load|sprite|hex|random|delay|key|-key|buzzer|native)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.other.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Statement keywords (SCHIP)</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:hires|lores|scroll-down|scroll-left|scroll-right|bighex|exit|saveflags|loadflags)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.other.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Statement keywords (XO-Chip)</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:long|plane|audio|scroll-up)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.other.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Binary numbers</string>
			<key>match</key>
			<string>(?&lt;=^|\s)[+\-]?0b[01]+(?=$|\s)</string>
			<key>name</key>
			<string>constant.numeric.binary.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hexadecimal numbers</string>
			<key>match</key>
			<string>(?&lt;=^|\s)[+\-]?0x\h+(?=$|\s)</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Decimal numbers</string>
			<key>match</key>
			<string>(?&lt;=^|\s)[+\-]?\d+(?=$|\s)</string>
			<key>name</key>
			<string>constant.numeric.decimal.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Subroutine names</string>
			<key>match</key>
			<string>(?&lt;=^|\s):\s+\S+(?=$|\s)</string>
			<key>name</key>
			<string>entity.name.function.octo</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.octo</string>
	<key>uuid</key>
	<string>facc0037-7506-4917-99cb-5f57a3c85728</string>
</dict>
</plist>
