<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>8o</string>
	</array>
	<key>name</key>
	<string>Octo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single line comments</string>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Data registers</string>
			<key>match</key>
			<string>\b(?i:v[0-9a-f])\b</string>
			<key>name</key>
			<string>variable.language.vreg.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Address register</string>
			<key>match</key>
			<string>\bi\b</string>
			<key>name</key>
			<string>variable.language.ireg.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assignment operators</string>
			<key>match</key>
			<string>\:=|\+=|\-=|=\-|\|=|&amp;=|\^=|&lt;&lt;=|&gt;&gt;=</string>
			<key>name</key>
			<string>keyword.operator.assignment.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comparison operators</string>
			<key>match</key>
			<string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control flow keywords</string>
			<key>match</key>
			<string>\b(?:return|if|then|begin|else|end|loop|again|while|jump|jump0)\b</string>
			<key>name</key>
			<string>keyword.control.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Return shorthand operator</string>
			<key>match</key>
			<string>(?:^|\s)\;(?:$|\s)</string>
			<key>name</key>
			<string>keyword.control.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Statement keywords (standard)</string>
			<key>match</key>
			<string>\b(?:clear|bcd|save|load|sprite|hex|random)\b</string>
			<key>name</key>
			<string>keyword.other.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Statement keywords (SCHIP)</string>
			<key>match</key>
			<string>\b(?:hires|lores|scroll-down|scroll-left|scroll-right|bighex|exit|saveflags|loadflags)\b</string>
			<key>name</key>
			<string>keyword.other.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Statement keywords (XO-Chip)</string>
			<key>match</key>
			<string>\b(?:long|plane|audio|scroll-up)\b</string>
			<key>name</key>
			<string>keyword.other.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Binary numbers</string>
			<key>match</key>
			<string>\b0b[01]+\b</string>
			<key>name</key>
			<string>constant.numeric.binary.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hexadecimal numbers</string>
			<key>match</key>
			<string>\b0x[0-9A-Fa-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.octo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Decimal numbers</string>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.octo</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.octo</string>
	<key>uuid</key>
	<string>facc0037-7506-4917-99cb-5f57a3c85728</string>
</dict>
</plist>
